name: fire_fighter
description: A simple Flame game.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flame: ^1.13.1
  flame_audio: ^2.1.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  flame_lint: 1.1.2
  flame_test: ^1.15.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/audio/
    - assets/images/fire/
    - assets/images/fire_engine/
    - assets/font/

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/font/PressStart2P-Regular.ttf