name: fire_fighter
description: A simple Flame game.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: 1.12.0
  flame_audio: 2.1.5
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: 1.1.2
  flame_test: 1.15.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/audio/
    - assets/images/fire/
    - assets/images/fire_engine/
    - assets/font/

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/font/PressStart2P-Regular.ttf